- name: k8s common setup
  become: true
  hosts: allworker
  tasks:
    - name: Install Containerd
      apt:
        name: containerd
        state: present
        update_cache: yes
    - name: Configure sysctl for k8s network
      copy:
      dest: /etc/sysctl.d/99-k8s-cri.conf
      content: |
		net.bridge.bridge-nf-call-iptables=1
        net.bridge.bridge-nf-call-ip6tables=1
        net.ipv4.ip_forward=1
    - name: set sysctl
      shell: |
	    sysctl --system
		modprobe overlay; modprobe br_netfilter
		echo -e overlay\\nbr_netfilter > /etc/modules-load.d/k8s.conf
		update-alternatives --set-selections iptables manual /usr/sbin/iptables-legacy
		swapoff -a
      become: yes
    - name: modify fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '(^[^#]*\b/swap.img\b)'
        replace: '#\1'
      backup: yes  # 기존 파일 백업
    - name: modify grub
      ansible.builtin.replace:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX=""'
        replace: 'GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"'
      backup: yes  # 기존 파일 백업    
    - name: Get Keyring of k8s
      shell: |
	    update-grub
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
    - name: Install k8s
      apt:
        - kubeadm
        - kubelet
        - kubectl
      state: present
      enabled: yes
      update_cache: yes
      
    - name: Setting for k8s 
      ansible.builtin.replace:
        path: /etc/default/kubelet
        regexp: '^KUBELET_EXTRA_ARGS=""'
        replace: 'KUBELET_EXTRA_ARGS="--cgroup-driver=cgroupfs"'
      backup: yes  # 기존 파일 백업
    - name: Setting for containerd
      ansible.builtin.replace:
        path: /usr/lib/systemd/system/containerd.service
        regexp: '^KillMode=none'
        replace: 'KillMode=mixed'
      backup: yes  # 기존 파일 백업
    - name: restart k8s and containerd
      shell: |
	    systemctl daemon-reload
		systemctl restart containerd.service
		systemctl restart kubelet
    - name: Install iscsi for longhorn
      apt:
        update_cache: yes
        name: open-iscsi
        state: present
        enabled: yes