- name: k8s common setup
  become: true
  hosts: master
  tasks:
    - name: Init k8s
      shell: |
        kubeadm init --pod-network-cidr=100.100.100.0/24 --cri-socket=unix:///run/containerd/containerd.sock
    - name: Generate Token and save join instruction inside variable
      command: kubeadm token create --print-join-command
      register: join_command
    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
    - debug: msg="{{ join_command }}"
    - name: get Calico settings example
      command: wget https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml
    - name: get Dashboard yaml example
      command: wget https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
    - name: get Longhorn setting file
      command: wget https://raw.githubusercontent.com/longhorn/longhorn/v1.7.1/deploy/longhorn.yaml

- name: Joining Job Step 2 on Worker1 node
  hosts: worker1
  become: true
  tasks:
    - name: Copy the join command to server location
      copy: src=join-command dest=/tmp/join-command.sh mode=0777
    - name: Join the node to cluster
      command: sh /tmp/join-command.sh
- name: Joining Job Step 2 on Worker2 node
  hosts: worker2
  become: true
  tasks:
    - name: Copy the join command to server location
      copy: src=join-command dest=/tmp/join-command.sh mode=0777
    - name: Join the node to cluster
      command: sh /tmp/join-command.sh
- name: Joining Job Step 2 on Worker3 node
  hosts: worker3
  become: true
  tasks:
    - name: Copy the join command to server location
      copy: src=join-command dest=/tmp/join-command.sh mode=0777
    - name: Join the node to cluster
      command: sh /tmp/join-command.sh
- name: Joining Job Step 2 on Worker4 node
  hosts: worker4
  become: true
  tasks:
    - name: Copy the join command to server location
      copy: src=join-command dest=/tmp/join-command.sh mode=0777
    - name: Join the node to cluster
      command: sh /tmp/join-command.sh
