- name: k8s common setup
  become: true
  hosts: master
  tasks:
    - name: Init k8s
      shell: |
        kubeadm init --pod-network-cidr=100.100.100.0/24 --cri-socket=unix:///run/containerd/containerd.sock
    - name: Generate Token and save join instruction inside Env Variable
      shell: |
        export JOIN=$(kubeadm token create --print-join-command)
    - name: shoot join to worker1
      shell: |
        ssh test@worker1 $JOIN
    - name: shoot join to worker1
      shell: |
        ssh test@worker2 $JOIN
    - name: shoot join to worker1
      shell: |
        ssh test@worker3 $JOIN
    - name: shoot join to worker1
      shell: |
        ssh test@worker4 $JOIN