- name: k8s common setup
  become: true
  hosts: all
  tasks:
    - name: Install Containerd
      apt:
        name:
          - containerd
          - apt-transport-https
          - ca-certificates
        state: present
        update_cache: yes
    - name: Configure sysctl for k8s network
      copy:
        dest: /etc/sysctl.d/99-k8s-cri.conf
        content: |
          net.bridge.bridge-nf-call-iptables=1
          net.bridge.bridge-nf-call-ip6tables=1
          net.ipv4.ip_forward=1
    - name: set sysctl
      shell: |
        sysctl --system
        modprobe overlay; modprobe br_netfilter
        echo -e overlay\\nbr_netfilter > /etc/modules-load.d/k8s.conf
    - name: Set iptables to legacy
      command: update-alternatives --config iptables
      args:
        creates: /etc/alternatives/iptables

    - name: Disable swap
      command: swapoff -a

    - name: Update fstab to disable swap on reboot
      lineinfile:
        path: /etc/fstab
        regexp: '^/swap.img'
        state: absent

    - name: Update GRUB configuration for cgroup
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX='
        line: 'GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"'
    - name: Update GRUB
      command: update-grub

    - name: Download the Kubernetes GPG key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: "0644"

    - name: Add Kubernetes Repo List
      apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
        state: present
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install k8s
      apt:
        name:
        - kubeadm
        - kubelet
        - kubectl
        state: present
        update_cache: yes

    - name: Configure kubelet to use cgroupfs
      lineinfile:
        path: /etc/default/kubelet
        regexp: '^KUBELET_EXTRA_ARGS='
        line: 'KUBELET_EXTRA_ARGS="--cgroup-driver=cgroupfs"'

    - name: Modify containerd service file
      lineinfile:
        path: /usr/lib/systemd/system/containerd.service
        regexp: '^KillMode='
        line: 'KillMode=mixed'
    - name: restart k8s and containerd
      shell: |
        systemctl daemon-reload
        systemctl restart containerd.service
        systemctl restart kubelet
    - name: Install iscsi for longhorn
      apt:
        update_cache: yes
        name: open-iscsi
        state: present
