apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongostore
  namespace: hgy
provisioner: driver.longhorn.io
parameters:
  dataLocality: disabled
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "5"
  staleReplicaTimeout: "30"