# 스테이트풀 셋 및 퍼시스턴스 볼륨 구성(스토리지 클래스 사전 준비 필요)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: hgy
spec:
  serviceName: "mongodb"
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      initContainers:
        - name: fix-permissions
          namespace: hgy
          image: busybox
          command: ["sh", "-c", "chown -R 999:999 /data/db"]
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db

      containers:
        - name: mongodb
          namespace: hgy
          image: mongo:latest
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - "rs0"
          ports:
            - containerPort: 27017
          envFrom:
          - configMapRef:
              name: mongo-cm 
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db

  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
        namespace: hgy
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: "mongostore"
            