apiVersion: v1
kind: ConfigMap
metadata:
  name: back-cm
  namespace: hgy
data:
  JWT_SECRET: "{{ .Values.backend.jwtSecret }}"
  JWT_EXPIRATION: "{{ .Values.backend.jwtExpire }}"
  DB_URL: "{{ .Values.backend.dbUrl }}"
  DB_USER: "{{ .Values.mariadb.username }}"
  DB_PASSWORD: "{{ .Values.mariadb.password }}"
  FILEPATH: '/'