apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: hgy
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.deployment.persistence.size }}
  storageClassName: "longhorn"