apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: hgy
spec:
  selector:
    type: db
  ports:
  - port: {{ .Values.dbservice.port }}
    targetPort: {{ .Values.dbservice.targetPort }}
  type: ClusterIP