apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-helm
  namespace: hgy
spec:
  selector:
    matchLabels:
      type: backend
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backimage.repository }}:{{ .Values.backimage.tag }}"
          namespace: hgy
          envFrom:
          - configMapRef:
              name: back-cm

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10