# templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: hgy
spec:
  replicas: {{ .Values.mongoReplicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongoimage.repository }}:{{ .Values.mongoimage.tag }}"
          namespace: hgy
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "{{ .Values.mongoauth.username }}"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "{{ .Values.mongoauth.password }}"
            - name: MONGO_INITDB_DATABASE
              value: "{{ .Values.mongoauth.database }}"
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: hgy
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.statefulset.persistence.size }}
        storageClassName: "longhorn"